package processor;

public enum Action {
    USER_CHOOSES_MAIN_MENU_ITEM,
    USER_CHOOSES_TRANSPOSE_MENU_ITEM,
    USER_ENTERS_MATRIX_SIZE,
    USER_ENTERS_MATRIX,
    USER_ENTERS_CONSTANT,
    EXIT
}
